### ISSUE TITLE
Google OAuth Policy Upgrade

### ISSUE THREAD

**Issue by ArshMalik02** [uclaacm/membership-portal#59]
## Issue

Google Cloud Platform (GCP) recently upgraded its policies regarding app verification. This update directly affects the membership portal as we use Google OAuth 2 to sign in/sign up users on the portal. Due to this change, users encounter an error as shown in the screenshot below- 

<img width="426" alt="Screenshot 2024-02-23 at 9 15 04 PM" src="https://github.com/uclaacm/membership-portal/assets/51771221/ea109b8e-b656-4401-ae09-6cd32da46c4c">

More details about the verification process and GCP can be found on this [support page](https://support.google.com/cloud/answer/7454865?hl=en). Currently, the GCP account used for auth is of a past dev team officer.

## Task

In order to comply with this policy and take the necessary action, we would have to migrate the project from the current gcp account to acm dev's gcp account (reach out to the current dev team director for credentials). This change will affect the docker container and the production build deployed on AWS EC2.

**Comment by snigdha-kansal** [comment]
It appears that this issue has been resolved as there have been no recent reports of users encountering this error. Additionally, the individual who originally reported this problem has confirmed that they are no longer experiencing it. Therefore, I am closing this issue. If the problem reoccurs, please feel free to reopen this issue or create a new one.
